msm8960: define HFP_ASM_RX_TX 24
Taken from hardware/qcom/audio-car/msm8960/hal/msm8969/platform.h
Fixes build error from android-7.1.2_r2 merge:
hardware/qcom/audio/default/hal/audio_extn/utils.c:150:25:
error: use of undeclared identifier 'HFP_ASM_RX_TX'
        pcm_device_id = HFP_ASM_RX_TX;

Change-Id: I6434c31b0310be87fa7c2128da5d641898787c4f

 Conflicts:
	hal/msm8960/platform.h

Signed-off-by: NoelMacwan <yulespencer@gmail.com>